### ISSUE TITLE
Beta Binaries, soon?

### ISSUE THREAD

**Issue by deavmi** [qaul/qaul.net_legacy#23]
Would oit be possible for some updated binaries in the GitHuba releases section?

**Comment by MathJud** [comment]
New betas will be published soon. 
It is bad praxis to publish binaries in a git repository, thats we don't publish them here anymore. 
The binaries will be available for download from the qaul.net web site.

**Comment by deavmi** [comment]
@MathJud Okay, thanks :smile:

**Comment by deavmi** [comment]
@MathJud Maybe you should get some autoamted building system, that can build the binaries for you, as I would really love to test out the betas, as the ones on the site seem quite outdated, idk?

Has much been happening in this project recently?

**Comment by MathJud** [comment]
qaul.net-ng will solve exactly this! We are porting the build system to Cmake to be able to produce the binaries automatically.

**Comment by deavmi** [comment]
@MathJud **YAY!**. Thanks :smile:.
