### ISSUE TITLE
Future of the project.

### ISSUE THREAD

**Issue by deavmi** [qaul/qaul.net_legacy#33]
Should we get more people involved, as I would love to see this project thrive. :smile:. It has been quite for quite a while now, maybe getting more people involved as I previously mentioned could lead to many new features, bug fixes and overall constant maintenance. :smile: Hnece I have posted this on reddit: http://www.reddit.com/r/Meshnet/comments/37018l/qualnet_i_want_this_project_to_thrive_check_it_out/

**Comment by deavmi** [comment]
Just realised that the ng version is being developed on. Sorry. :smile: :heart:

**Comment by MathJud** [comment]
you're welcome! 
Please pay attention on the correct spelling of the project name: qaul.net

**Comment by deavmi** [comment]
@MathJud Will do. Thanks.
