### ISSUE TITLE
Possible build of the qaul.net GUI client for the RaspberryPi

### ISSUE THREAD

**Issue by deavmi** [qaul/qaul.net_legacy#38]
Maybe if you could get some [updated builds](https://github.com/WachterJud/qaul.net/issues/23) up and also at the same time, build the GUI client for the Raspberry Pi 2 Model B architecture, as it will run easily on these machines.

**Thanks**,
Deavmi :smile:

**Comment by MathJud** [comment]
OK! I will try! 
Until now the Raspberry is supported as Server only - but it should't be a problem to change that.
How would you like to use it? with an USB wifi stick? Or over Ethernet?

**Comment by deavmi** [comment]
@MathJud USB Wifi Stick. I use an Edimax one. It works on my desktop, and is picked up by my Pi's current GNU/Linux distribution, Ubuntu Mate. SO I think it will work, obviously drivers has nothing really to do with this, it's all about getting a build out.

I have a Dekstop Environment, so It will be useable in the GUI mode (for the client).

**Comment by deavmi** [comment]
- Typo: Raspberry Pi Model **B**

**Comment by MathJud** [comment]
qaul.net-ng builds and works now on Raspberry Pi 2 with Ubuntu Mate desktop.
There are no binaries for Raspberry Pi yet. But it should be easy to build.
Please follow the documentation file:  https://github.com/WachterJud/qaul.net-ng/blob/qaul-ng/README_Raspberry_UbuntuMate.md
Looking forward to your test report!

**Comment by deavmi** [comment]
Yay! :) I ought to try that out soon! :)

---

Sent from Deavmi
Keep on hacking...

Contact Deavmi via:

Pjuu: https://pjuu.com/deavmi
GNU Social: deavmi@quitter.se
Twitter: https://twitter.com/deavmi
Main mailbox: deavmi@openmailbox.org
