### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by deavmi** [qaul/qaul.net_legacy#45]
Is qaul.net fully decentralized, in routing and IP addresses and such. The routing I assume so as of the use of olsr.

**Comment by MathJud** [comment]
yes! The routing decisions are done on every device independently due to the received HELLO messages from its neighbours. The routing protocol is OLSR .
The IP addresses are chosen randomly.

**Comment by deavmi** [comment]
So there is no like super node that does dhcp for the other nodes up addresses, it's all random. That's great! :) thanks.

---

Sent from Deavmi
Keep on hacking...

Contact Deavmi via:

Pjuu: https://pjuu.com/deavmi
GNU Social: deavmi@quitter.se
Twitter: https://twitter.com/deavmi
Main mailbox: deavmi@openmailbox.org
